server:
  port: 7002


spring:
  application:
    name: eureka-server7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    # 表示是都向 eureka server 注册服务
    # false：不会向注册中心注册自己，自己就是注册中心
    register-with-eureka: false
    # false: 不需要去检索服务
    fetch-registry: false
    service-url:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://eureka7001.com:7001/eureka


